
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PJ
 */
public class CustomerListFrame extends javax.swing.JPanel {

    /**
     * Creates new form ListAllCust
     */
    public CustomerListFrame() {
        initComponents();
        getTableContents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listCustomers = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 102, 102));
        setMinimumSize(new java.awt.Dimension(740, 450));

        listCustomers.setBackground(new java.awt.Color(255, 255, 51));
        listCustomers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer Num", "Customer Name", "Customer Surname", "Customer Phone", "Credit", "Can Rent"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(listCustomers);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private static DefaultTableModel model;
    
    
public void getTableContents(){
    
       ClientMainMenu clientListView = new ClientMainMenu(); 
       
       ArrayList<Customer> list = new ArrayList<Customer>(clientListView.customerTable());
       //sorts the ArrayList in alphabetical order
       Collections.sort(list, new Comparator<Customer>()
       {
           @Override
           public int compare(Customer t, Customer t1) 
           {
               return t.getName().compareTo(t1.getName()); 
           }
       
       });
       
       
       
       //populates the table from the arrayList
        model = (DefaultTableModel) listCustomers.getModel();
        model.setRowCount(0);
        for(int a = 0; a<list.size(); a++)
        {
            model.addRow(new Object[]{list.get(a).getCustNumber(), list.get(a).getName(),list.get(a).getSurname(), list.get(a).getPhoneNum(),list.get(a).getCredit(), list.get(a).canRent()});
        }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listCustomers;
    // End of variables declaration//GEN-END:variables
}
