
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author stean
 */
public class OutstandingReportFrame extends javax.swing.JPanel {

    /**
     * Creates new form OutStanding
     */
    public OutstandingReportFrame() {
        initComponents();
        populateTable(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        outstandingTable = new javax.swing.JTable();
        btnOutReport = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 102, 102));
        setMinimumSize(new java.awt.Dimension(850, 500));
        setPreferredSize(new java.awt.Dimension(850, 500));

        outstandingTable.setBackground(new java.awt.Color(255, 255, 51));
        outstandingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rental Number", "Date Rented", "Date Returned", "Customer Number", "DVD Number"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(outstandingTable);

        btnOutReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save report.png"))); // NOI18N
        btnOutReport.setContentAreaFilled(false);
        btnOutReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOutReportActionPerformed(evt);
            }
        });

        jLabel1.setText("Outstanding report");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(325, 325, 325)
                        .addComponent(btnOutReport))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(360, 360, 360)
                        .addComponent(jLabel1)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnOutReport)
                .addContainerGap(82, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnOutReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOutReportActionPerformed
      
        String filePath; 
        Date date1 = new Date();
        SimpleDateFormat dFormat = new SimpleDateFormat("yyyy-MM-dd HH-mm-ss") ;
        String date = dFormat.format(date1); 
        String fileName = "\\" + "(Outstanding rentals for)" + date + ".txt"; 
        
        
        JFileChooser fChooser = new JFileChooser();
        fChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        fChooser.showSaveDialog(this); 
        
        try
        {
            filePath = fChooser.getSelectedFile().getCanonicalPath(); 


            FileWriter fw = new FileWriter(filePath+fileName); 
            out = new BufferedWriter(fw); 
            out.write(String.format("%-20s", "Rantal Number") + String.format("%-20s", "Date Rented") + String.format("%-20s", "Date Returned") + String.format("%-20s", "Customer Number") + String.format("%-20s", "DVD Number"));
            out.newLine();
            
            out.write("_________________________________________________________________________");

            out.newLine();
            
            for(int cnt = 0; cnt<outstandingTable.getRowCount(); cnt++)
            {
                out.newLine();
                for(int cnt1 = 0; cnt1<5; cnt1++)
                {
                    String outstandingData = String.format("%-20s", outstandingTable.getValueAt(cnt, cnt1).toString()); 
                    out.write(outstandingData);
                }    
            }
        
        
        out.close();
        }catch(IOException e){
        }catch(NullPointerException e){
        
        }
        
       
        
    }//GEN-LAST:event_btnOutReportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOutReport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable outstandingTable;
    // End of variables declaration//GEN-END:variables
    private static DefaultTableModel model;
    private static Date date1, date2; 
    private static DateFormat df = new SimpleDateFormat("yyyy/mm/dd");
    private static BufferedWriter out = null;     
    public void populateTable(){
    
     ClientMainMenu view = new ClientMainMenu(); 
     ArrayList<Rental> rentals = new ArrayList<Rental>(view.rentals("NA"));
      
     Collections.sort(rentals, new Comparator<Rental>(){
        @Override        
                public int compare(Rental t, Rental t1) {
                    
                  return t1.getDateRented().compareTo(t.getDateRented());  
                }
           
       
       });
      
       //populates the table from the arrayList
        model = (DefaultTableModel) outstandingTable.getModel();
        model.setRowCount(0);
        for(int a = 0; a<rentals.size(); a++){
        model.addRow(new Object[]{rentals.get(a).getRentalNumber(), rentals.get(a).getDateRented(), 
        rentals.get(a).getDateReturned(), rentals.get(a).getCusNumber(), rentals.get(a).dvdNumber()});
    }
}

}